version: "3.8"

services:
  
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=jlbeltrang
      - POSTGRES_PASSWORD=josel1966
      - POSTGRES_DB=db_test

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'jlbeltrang@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'josel1966'
    ports:
      - "80:80"
    depends_on:
      - postgres



